# Generated by Django 4.2 on 2025-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_perfect', models.BooleanField()),
                ('is_prime', models.BooleanField()),
                ('properties', models.CharField(max_length=255)),
                ('digital_sum', models.IntegerField()),
                ('fun_fact', models.CharField(max_length=255)),
            ],
        ),
    ]
